package com.cinetrack.movie;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Array;
import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.util.Map;
import java.util.UUID;

/**
 * Movie entity demonstrating Hibernate 7 features:
 * <ul>
 *   <li>{@link UuidGenerator}: RFC-4122 UUID generated by Hibernate (no DB sequence needed)</li>
 *   <li>{@link JdbcTypeCode}(SqlTypes.JSON): maps {@code Map<String,Object>} to a JSONB column</li>
 *   <li>{@link Array}: maps {@code String[]} to a PostgreSQL TEXT[] column</li>
 *   <li>{@link BatchSize}: prevents N+1 when loading collections of movies</li>
 * </ul>
 */
@Entity
@Table(name = "movies")
@BatchSize(size = 25)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"metadata", "streamingPlatforms"})
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Movie {

    /**
     * Hibernate 7 generates a UUID v4 value before INSERT, so the entity has
     * its identity immediately after {@code persist()}: no round-trip needed.
     */
    @Id
    @UuidGenerator
    @EqualsAndHashCode.Include
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "title", nullable = false, length = 500)
    private String title;

    /**
     * Stored as VARCHAR; Hibernate maps the enum name by default.
     * Using {@code EnumType.STRING} makes migrations readable and safe
     * against enum reordering.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "genre", nullable = false, length = 50)
    private Genre genre;

    @Column(name = "release_year", nullable = false)
    private int releaseYear;

    @Column(name = "rating", precision = 3, scale = 1)
    private BigDecimal rating;

    /**
     * Hibernate 7 JSON mapping: the Map is serialised to JSONB on write and
     * deserialised on read via the built-in {@code JsonJdbcType}. No extra
     * library required when the PostgreSQL JDBC driver is on the classpath.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "metadata", columnDefinition = "jsonb")
    private Map<String, Object> metadata;

    /**
     * Hibernate 7 array support: maps directly to PostgreSQL TEXT[].
     * The {@code @Array} annotation lets Hibernate know the max length hint;
     * the actual DDL column type is derived from the element type.
     */
    @Array(length = 20)
    @Column(name = "streaming_platforms", columnDefinition = "text[]")
    private String[] streamingPlatforms;

    @Version
    @Column(name = "version", nullable = false)
    private long version;
}
