package com.cinetrack.movie;

import com.querydsl.jpa.impl.JPAQueryFactory;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Demonstrates QueryDSL-JPA as an alternative to {@link MovieSpecifications}.
 *
 * <h2>Trade-offs vs Specifications</h2>
 * <table border="1">
 *   <tr><th>Dimension</th><th>Specifications</th><th>QueryDSL</th></tr>
 *   <tr><td>Type safety</td><td>Metamodel attributes</td><td>Generated Q-types</td></tr>
 *   <tr><td>Composability</td><td>{@code and()}/{@code or()}</td><td>{@code BooleanExpression}</td></tr>
 *   <tr><td>Join control</td><td>CriteriaQuery joins</td><td>{@code query.join()} / {@code fetchJoin()}</td></tr>
 *   <tr><td>Projections</td><td>Limited</td><td>Full DTO projection via {@code Projections.*}</td></tr>
 * </table>
 *
 * <p>The {@code QMovie} class is generated by the APT Maven plugin configured
 * in {@code pom.xml}. Run {@code mvn compile} to produce it under
 * {@code target/generated-sources/java/com/cinetrack/movie/QMovie.java}.</p>
 */
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class MovieQuerydslService {

    private final JPAQueryFactory queryFactory;

    /**
     * Returns all movies released between {@code fromYear} and {@code toYear}
     * (inclusive), ordered by release year ascending then title.
     *
     * <p>The generated SQL is equivalent to:</p>
     * <pre>{@code
     * SELECT * FROM movies
     *  WHERE release_year >= fromYear
     *    AND release_year <= toYear
     *  ORDER BY release_year ASC, title ASC
     * }</pre>
     *
     * @param fromYear lower bound (inclusive)
     * @param toYear   upper bound (inclusive)
     * @return matching movies, ordered
     */
    public List<Movie> findMoviesReleasedBetween(int fromYear, int toYear) {
        QMovie movie = QMovie.movie;

        return queryFactory
                .selectFrom(movie)
                .where(
                    movie.releaseYear.goe(fromYear),
                    movie.releaseYear.loe(toYear)
                )
                .orderBy(
                    movie.releaseYear.asc(),
                    movie.title.asc()
                )
                .fetch();
    }

    /**
     * Returns movies matching an optional genre and a minimum rating.
     * Either parameter may be {@code null} to skip that filter — QueryDSL
     * silently ignores {@code null} predicates passed to {@code where()}.
     */
    public List<Movie> findByGenreAndMinRating(Genre genre, Double minRating) {
        QMovie movie = QMovie.movie;

        return queryFactory
                .selectFrom(movie)
                .where(
                    genre     != null ? movie.genre.eq(genre)                                : null,
                    minRating != null ? movie.rating.goe(new java.math.BigDecimal(minRating.toString())) : null
                )
                .orderBy(movie.rating.desc().nullsLast())
                .fetch();
    }
}
