package com.cinetrack.user;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.UuidGenerator;

import java.util.UUID;

/**
 * AppUser uses a time-ordered UUID (version 7) as its primary key.
 * UuidGenerator.Style.TIME produces monotonically increasing values,
 * which keeps B-tree index pages from fragmenting the way random UUIDs do.
 * The UUID is generated by Hibernate before the INSERT, so no round-trip
 * is needed to retrieve the generated key — unlike IDENTITY columns.
 */
@Entity
@Table(name = "app_users")
@Getter
@Setter
@NoArgsConstructor
public class AppUser {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(columnDefinition = "UUID")
    private UUID id;

    @Column(unique = true, nullable = false, length = 100)
    private String username;

    @Column(unique = true, nullable = false)
    private String email;

    public AppUser(String username, String email) {
        this.username = username;
        this.email = email;
    }
}
