-- Chapter 4: Hibernate 7 Internals — schema

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── movies ───────────────────────────────────────────────────────────────────
-- UUID primary key generated by Hibernate's @UuidGenerator(style=TIME).
-- metadata   : arbitrary JSONB key/value pairs (release info, awards, etc.)
-- streaming_platforms : PostgreSQL TEXT[] mapped via Hibernate @Array
CREATE TABLE movies (
    id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    title               VARCHAR(255) NOT NULL,
    genre               VARCHAR(50)  NOT NULL,
    release_year        INT          NOT NULL,
    rating              NUMERIC(3,1),
    metadata            JSONB,
    streaming_platforms TEXT[],
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

-- ── app_users ────────────────────────────────────────────────────────────────
CREATE TABLE app_users (
    id              BIGSERIAL    NOT NULL,
    username        VARCHAR(100) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

-- ── reviews ──────────────────────────────────────────────────────────────────
CREATE TABLE reviews (
    id          BIGSERIAL    NOT NULL,
    movie_id    UUID         NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    reviewer_id BIGINT       NOT NULL REFERENCES app_users(id),
    content     TEXT,
    rating      NUMERIC(3,1) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

-- ── series ───────────────────────────────────────────────────────────────────
-- cast_info : JSONB array of cast member names mapped as List<String>
CREATE TABLE series (
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    title       VARCHAR(255) NOT NULL,
    cast_info   JSONB,
    seasons     INT          NOT NULL DEFAULT 1,
    CONSTRAINT pk_series PRIMARY KEY (id)
);
