spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cinetrack}
    username: ${DB_USER:cinetrack}
    password: ${DB_PASS:cinetrack}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        search:
          backend:
            type: lucene
            directory:
              type: local-filesystem
              root: ./search-index
  flyway:
    enabled: true
    locations: classpath:db/migration
