spring.application.name=chapter-10-jpql-queries

spring.datasource.url=jdbc:postgresql://localhost:5432/cinetrack
spring.datasource.username=cinetrack
spring.datasource.password=cinetrack

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
