spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinetrack
    username: cinetrack
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
          jcache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: ehcache.xml

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.stat: DEBUG
    org.hibernate.cache: DEBUG
    com.cinetrack: DEBUG
